# Generated by Django 3.2.1 on 2022-04-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daycareapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='profile',
        ),
    ]
